name: supabase_dart_client
description: Dart client for Supabase with ORM-like features (runtime components)
version: 0.2.0
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  http: ^1.4.0
  supabase: ^2.7.0
  meta: ^1.9.1
  uuid: ^4.4.2
  path: ^1.8.3
  collection: ^1.17.2
  json_annotation: ^4.9.0
  
dev_dependencies:
  test: ^1.24.1
  mockito: ^5.4.2
  lints: ^2.1.1
  json_serializable: ^6.7.1
